name: sidemenfilm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50198
title: 'Sidemen: Long Road to Glory'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#808080'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.10961641903515429
  saturation: 0.13182389043583742
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
